USE [master]
GO

CREATE DATABASE [medical]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'medical', FILENAME = N'/var/opt/mssql/data/medical.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'medical_log', FILENAME = N'/var/opt/mssql/data/medical_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [medical] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [medical].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [medical] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [medical] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [medical] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [medical] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [medical] SET ARITHABORT OFF 
GO

ALTER DATABASE [medical] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [medical] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [medical] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [medical] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [medical] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [medical] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [medical] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [medical] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [medical] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [medical] SET  DISABLE_BROKER 
GO

ALTER DATABASE [medical] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [medical] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [medical] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [medical] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [medical] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [medical] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [medical] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [medical] SET RECOVERY FULL 
GO

ALTER DATABASE [medical] SET  MULTI_USER 
GO

ALTER DATABASE [medical] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [medical] SET DB_CHAINING OFF 
GO

ALTER DATABASE [medical] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [medical] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [medical] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [medical] SET QUERY_STORE = OFF
GO

ALTER DATABASE [medical] SET  READ_WRITE 
GO

-- create user and map it to the database
CREATE LOGIN [medical-db-user] WITH PASSWORD=N'password', DEFAULT_DATABASE=[medical], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE medical
GO

CREATE USER [medical-db-user] FOR LOGIN [medical-db-user] WITH DEFAULT_SCHEMA=[dbo]
GO

exec sp_addrolemember 'db_datareader', 'medical-db-user';
GO

exec sp_addrolemember 'db_datawriter', 'medical-db-user';
GO